### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [posva/vuefire-nuxt-example#1]
Hey i tried many methods to install firebase in nuxt however everything firebase data loads after page load. I want both together

**Comment by posva** [comment]
Check VueFire docs and this example. Unless there is authentication involved, the date is rendered with the page. With Authentication it’s a bit more complicated but not impossible

**Comment by rahulkumarsingh73690** [comment]
Uploading Nuxt + VueFire - Google Chrome 2023-06-27 12-53-54.mp4…

**Comment by rahulkumarsingh73690** [comment]
https://github.com/posva/vuefire-nuxt-example/assets/37482171/86f64fce-0fc4-4774-8029-ae3f8c1221b6

**Comment by rahulkumarsingh73690** [comment]
See here data loads after page load. Thanks for demo
