### ISSUE TITLE
demo app login is not working

### ISSUE THREAD

**Issue by itai-gendler** [posva/vuefire-nuxt-example#2]
hello.
i'm trying out the deployed demo: https://vuefire-nuxt.firebaseapp.com/login
but when trying to login, either with popup or redirect it is not working
looks like it failing on 401 on api/session endpoint

![image](https://github.com/posva/vuefire-nuxt-example/assets/16039521/44ff9f3e-c5f0-4ea6-b649-021f863516e9)

for me when i'm trying the solution locally it works, but when i deploy to firebase it is also not working. but in my case the error is that api/session gets 404. what am i doing wrong?
![image](https://github.com/posva/vuefire-nuxt-example/assets/16039521/c1df5970-9022-40f6-8b28-34c55efcdda8)

thanks for the great example, just really want to get it to work.

**Comment by posva** [comment]
Yes, missing credentials I cannot generate in this project.

You can check this example instead: https://github.com/posva/nuxt--vuefire-example-spark-plan it also works with emulators to test locally 👍 

Your error is probably because of misconfiguration of auth without ssr but with ssr activated.

**Comment by itai-gendler** [comment]
thanks for the reply, i will be checking it.
what do you mean by `auth without ssr but with ssr activated` ?

i have ssr enabled and auth enabled as well. when working locally i have a service-account.json file and and env var `GOOGLE_APPLICATION_CREDENTIALS` pointing to it.
what should i do when i run `firebase deploy`?

also small question in the spark repo you have a link to a blaze example, i guess you are reffering to this repository right? because the link goes to a 404 repo: `https://github.com/posva/nuxt--vuefire-example-blaze-plan`

thanks for the amazing fast help! your awsome!

**Comment by posva** [comment]
ah, right, it's still private! I still need to wait a bit before publishing it.

the api endpoint exists in a Blaze plan with cloud functions, maybe you are on a spark plan, in which case you should deploy a `nuxt generate` version and not prerender every page. you need to activate some features on the firebase console too. I will have a version with documentation very soon. BTW, note you also have https://bandator-d9c35.web.app

**Comment by itai-gendler** [comment]
actually i have upgraded to blaze plan. because when i tried to deploy as it is it complained so i just went and updated.

also this url doesn't work `https://bandator-d9c35.web.app/`.

anyways is the new blaze-plan repo is basically just next evolution of this example? if yes i will just wait for it, and meanwhile i will tryout the spark example.

again thanks for such amazing responses, out of words.

**Comment by posva** [comment]
The blaze version is pretty much the same as the spark version but with a nitro preset that is not yet available

**Comment by itai-gendler** [comment]
so is this example basically obsolete?

**Comment by posva** [comment]
No

**Comment by itai-gendler** [comment]
i'm a bit confused.
can you share what is the difference between this example and the new one?
which should be used for what scenario?
